# Specify docker image
image: debian:stretch

# Define variable to disable SSL verification of GIT
variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - test
  - transifex

# Generate perlcritic rapport
create_perlcritic_rapport:
  stage: test
  only:
    - branches
    - tags
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq libperl-critic-perl
  script:
    - cp contrib/bin/fusiondirectory-setup contrib/bin/fusiondirectory-setup.pl
    - cp contrib/bin/fusiondirectory-insert-schema contrib/bin/fusiondirectory-insert-schema.pl
    - perlcritic --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" contrib/bin

# generate man pages to test validity
test_manpages:
  stage: test
  only:
    - branches
    - tags
  script:
    - pod2man -c "FusionDirectory Documentation" -r "FusionDirectory 1.3" contrib/bin/fusiondirectory-insert-schema contrib/man/fusiondirectory-insert-schema.1
    - pod2man -c "FusionDirectory Documentation" -r "FusionDirectory 1.3" contrib/bin/fusiondirectory-setup contrib/man/fusiondirectory-setup.1
    - pod2man -c "FusionDirectory Documentation" -r "FusionDirectory 1.3" contrib/man/fusiondirectory.conf.pod contrib/man/fusiondirectory.conf.5
    - lexgrog contrib/man/fusiondirectory-insert-schema.1
    - lexgrog man/fusiondirectory.conf.5
    - lexgrog man/fusiondirectory-setup.1

# PHP codesniffer
create_php_code_sniffer_rapport:
  stage: test
  only:
    - branches
    - tags
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq  git php-cli php-codesniffer
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - find . -type f -name '*.php' -o -name '*.inc' -exec phpcs --standard=../dev-tools/php-codesniffer-rules/FDStandard/ruleset.xml "{}" \;

# PHP lint
create_php_lint_rapport:
  stage: test
  only:
    - branches
    - tags
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq php-cli
  script:
    - find . -type f -name '*.php' -o -name '*.inc' -print0 | xargs -0 -n1 php -l

# fusiondirectory-update-locale
fusiondirectory-update-locale:
  stage: test
  only:
    - branches
    - tags
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gettext git php-cli
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale -g

# Update transifex
update-transifex:
  stage: transifex
  only:
    - 1.3-dev
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gettext git php-cli transifex-client
  script:
    - git clone https://gitlab.fusiondirectory.org/fusiondirectory/dev-tools.git ../dev-tools
    - echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
    - tx pull -a -f
    - ../dev-tools/locale-scripts/fusiondirectory-update-locale -g
    - tx push -f -s -t --skip --no-interactive
